### ISSUE TITLE
Problem resolving Docker Hub domains

### ISSUE THREAD

**Issue by mtneug** [Parallels/docker-machine-parallels#11]
I have trouble seaching/pulling images form Docker Hub. Most of the time (but not always) I get this message:

```sh
$ docker search busybox
Error response from daemon: Get https://index.docker.io/v1/search?q=busybox: dial tcp: lookup index.docker.io: no such host
```
```sh
$ docker pull busybox
Using default tag: latest
latest: Pulling from library/busybox
039b63dd2cba: Pulling fs layer
c51f86c28340: Pulling fs layer
Pulling repository docker.io/library/busybox
Get https://registry-1.docker.io/v1/repositories/library/busybox/tags/latest: dial tcp: lookup registry-1.docker.io: no such host
```

Because resolution was succeeding at times, I was able to pull an ubuntu image and install `dnsutils`. When resolving `index.docker.io` or `registry-1.docker.io` most of the time I got results similar to these:

```sh
$ dig index.docker.io
;; Got bad packet: extra input data
212 bytes
7f fe 81 80 00 01 00 05 00 00 00 01 05 69 6e 64          .............ind
65 78 06 64 6f 63 6b 65 72 02 69 6f 00 00 01 00          ex.docker.io....
01 c0 0c 00 05 00 01 00 00 01 22 00 1e 06 65 6c          .........."...el
62 2d 69 6f 09 75 73 2d 65 61 73 74 2d 31 03 61          b-io.us-east-1.a
77 73 04 64 63 6b 72 c0 19 c0 2d 00 05 00 01 00          ws.dckr...-.....
00 02 49 00 44 26 75 73 2d 65 61 73 74 2d 31 2d          ..I.D&us-east-1-
65 6c 62 69 6f 2d 72 6d 35 62 6f 6e 31 71 61 65          elbio-rm5bon1qae
6f 34 2d 36 32 33 32 39 36 32 33 37 09 75 73 2d          o4-623296237.us-
65 61 73 74 2d 31 03 65 6c 62 09 61 6d 61 7a 6f          east-1.elb.amazo
6e 61 77 73 03 63 6f 6d 00 c0 55 00 01 00 01 00          naws.com..U.....
00 00 32 00 04 34 01 f2 ec c0 55 00 01 00 01 00          ..2..4....U.....
00 00 32 00 04 36 ad 6f db c0 55 00 01 00 01 00          ..2..6.o..U.....
00 00 32 00 04 34 05 24 19 00 00 29 05 00 00 00          ..2..4.$...)....
00 00 00 00                                              ....
```

```sh
$ dig registry-1.docker.io
;; Got bad packet: extra input data
275 bytes
43 0b 81 80 00 01 00 08 00 00 00 01 0a 72 65 67          C............reg
69 73 74 72 79 2d 31 06 64 6f 63 6b 65 72 02 69          istry-1.docker.i
6f 00 00 01 00 01 c0 0c 00 05 00 01 00 00 01 2a          o..............*
00 24 0c 65 6c 62 2d 72 65 67 69 73 74 72 79 09          .$.elb-registry.
75 73 2d 65 61 73 74 2d 31 03 61 77 73 04 64 63          us-east-1.aws.dc
6b 72 c0 1e c0 32 00 05 00 01 00 00 03 82 00 48          kr...2.........H
2a 75 73 2d 65 61 73 74 2d 31 2d 65 6c 62 72 65          *us-east-1-elbre
67 69 73 2d 31 30 66 75 63 73 76 6a 31 74 63 67          gis-10fucsvj1tcg
79 2d 31 33 33 38 32 31 38 30 30 09 75 73 2d 65          y-133821800.us-e
61 73 74 2d 31 03 65 6c 62 09 61 6d 61 7a 6f 6e          ast-1.elb.amazon
61 77 73 03 63 6f 6d 00 c0 60 00 01 00 01 00 00          aws.com..`......
00 3a 00 04 34 01 63 34 c0 60 00 01 00 01 00 00          .:..4.c4.`......
00 3a 00 04 36 d2 3b b2 c0 60 00 01 00 01 00 00          .:..6.;..`......
00 3a 00 04 36 d2 f3 09 c0 60 00 01 00 01 00 00          .:..6....`......
00 3a 00 04 34 05 56 fe c0 60 00 01 00 01 00 00          .:..4.V..`......
00 3a 00 04 34 16 6d 32 c0 60 00 01 00 01 00 00          .:..4.m2.`......
00 3a 00 04 36 56 7e 38 00 00 29 05 00 00 00 00          .:..6V.8..).....
00 00 00                                                 ...
```

The same output was produced form a statically compiled `dig` running directly in the VM (downloaded from [here](https://github.com/sequenceiq/docker-alpine-dig)). Strangely `nslookup` works from the VM (preinstalled) but fails from within the container.

```sh
vm$ nslookup index.docker.io
Server:    10.211.55.1
Address 1: 10.211.55.1

Name:      index.docker.io
Address 1: 52.1.242.236 ec2-52-1-242-236.compute-1.amazonaws.com
Address 2: 52.5.36.25 ec2-52-5-36-25.compute-1.amazonaws.com
Address 3: 54.173.111.219 ec2-54-173-111-219.compute-1.amazonaws.com
```

```sh
container$ nslookup index.docker.io
;; Got bad packet: extra input data
201 bytes
52 80 81 80 00 01 00 05 00 00 00 00 05 69 6e 64          R............ind
65 78 06 64 6f 63 6b 65 72 02 69 6f 00 00 01 00          ex.docker.io....
01 c0 0c 00 05 00 01 00 00 01 13 00 1e 06 65 6c          ..............el
62 2d 69 6f 09 75 73 2d 65 61 73 74 2d 31 03 61          b-io.us-east-1.a
77 73 04 64 63 6b 72 c0 19 c0 2d 00 05 00 01 00          ws.dckr...-.....
00 01 94 00 44 26 75 73 2d 65 61 73 74 2d 31 2d          ....D&us-east-1-
65 6c 62 69 6f 2d 72 6d 35 62 6f 6e 31 71 61 65          elbio-rm5bon1qae
6f 34 2d 36 32 33 32 39 36 32 33 37 09 75 73 2d          o4-623296237.us-
65 61 73 74 2d 31 03 65 6c 62 09 61 6d 61 7a 6f          east-1.elb.amazo
6e 61 77 73 03 63 6f 6d 00 c0 55 00 01 00 01 00          naws.com..U.....
00 00 23 00 04 36 ad 6f db c0 55 00 01 00 01 00          ..#..6.o..U.....
00 00 23 00 04 34 05 24 19 c0 55 00 01 00 01 00          ..#..4.$..U.....
00 00 23 00 04 34 01 f2 ec                               ..#..4...
```

Resolution on my host system or from a newly created VM on VirtualBox works just fine. Also I am able to resolve at least `google.com` and `archive.ubuntu.com` without problems. Changing the used DNS server in `/etc/resolv.conf` to `8.8.8.8` and restarting the Docker Daemon fixes the problem, but this is reseted on the next reboot by the DHCP client `udhcpc`.

My current setup:

* OS X: `10.11.2 Beta (15C31f)`
* Parallels Desktop 11 Pro Edition: `11.0.2 (31348)`
* boot2docker: `1.9.0 master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015`

**Comment by mtneug** [comment]
The DNS server can be changed automatically on reboot by adding these lines to `/var/lib/boot2docker/profile`:

```sh
echo \
'search <search-domain>
nameserver <DNS server ip>' > /etc/resolv.conf
```

This workaround fixes my problem. Still it would be better if the Parallels DNS server would give me correct responses. By the way, setting the `--dns` flag of the Docker Daemon does not work. It seams Docker is not using it for searching/pulling.

**Comment by legal90** [comment]
@mtneug Thanks for reporting this issue. I'd like to reproduce this issue prior to report it to our R&D. 
Have you managed to find some reproduction scenario? 
Do you have any idea - what actions may cause this issue? May be, it occurs after some other VM manipulations (start/stop/etc.)?

**Comment by krasilich** [comment]
Let me share my thoughts on this.
I still see this issue from time to time, but now it is not occure on parallels only, but on virtualbox as well.
Another thing I noticed, that when it happens I have more than one machine running (no matter if them of the same driver or not) maybe it's somehow related.
For me it happens not to often (once on a couple of days) and lasts for a couple of hours, so I tended to think that its something with my connection or with docker services availability.

**Comment by mtneug** [comment]
@legal90 Actually there was an issue before, but I hope it is unrelated. I upgraded form Parallels 10 to Parallels 11 because of the Docker support. I wanted to start the boot2docker VM automatically. Parallels told me for that I need to activate the "Start Parallels Desktop as a service" setting. But after the required newstart, Parallels was not able to start anymore. At that point I completely uninstalled Parallels (including setting/licenses/etc. files in `/Library/Preferences/` and `~/Library/Preferences/`) and installed it again. The setting worked after that.

To reproduce I again started from scratch:

1. Completely uninstall Parallels
2. Reboot
3. Install Parallels
4. Reboot
5. Create a boot2docker VM: `docker-machine create --driver=parallels --parallels-cpu-count=4 --parallels-disk-size=50000 --parallels-memory=4096 dev`
6. SSH into the VM: `docker-machine ssh dev`
7. Download `dig`: `curl -L https://github.com/sequenceiq/docker-alpine-dig/releases/download/v9.10.2/dig.tgz|tar -xzv -C .`
8. Resolve a domain: `./dig <domain>`

I noticed that the resolution always succeeds, when the response is an A record. So `google.com` or `docker.io` work perfectly. However, in case of a CNAME the `dig` complains with the message in the first post. `index.docker.io` and `registry-1.docker.io` are both CNAME records. I set up a CNAME hierarchy with `www3.mtneug.de` -> `www2.mtneug.de` -> `www1.mtneug.de` -> `mtneug.de`. For every additional domain, `dig` complained about 19 additional bytes.

Also I created an Ubuntu server VM with the [official image (iso)](http://releases.ubuntu.com/14.04.3/ubuntu-14.04.3-server-amd64.iso) and an express installation. The preinstalled `dig` has the same output.

Currently I'm at my University where resolution seem to work fine. I will check again when I'm home. Also I will check with a different machine.

**Comment by legal90** [comment]
@mtneug @krasilich 
Thank you for details! This issue was caught and fixed by Parallels team.
The fix will be released in the scope of the next update for Parallels Desktop 11, which is coming very soon. I will let you know about this.

**Comment by mtneug** [comment]
@legal90 :+1: Thank you for your help! I'm looking forward to the patch :shipit:.

Just to be clear that we are talking about the same bug: I analyzed the DNS packages Parallels is proxying to the VM. It seems Parallels is always making use of [DNS name compression](https://tools.ietf.org/html/rfc1035#section-4.1.4) even if the DNS server my host is using does not. I use [`dnsmasq`](http://www.thekelleys.org.uk/dnsmasq/doc.html) at home, which is answering with a fully expanded name, e.g. `mtneug.de`. In this example it's setting a [`RDLENGTH`](https://tools.ietf.org/html/rfc1035#section-4.1.3) of 11 bytes. Parallels then seems to compress the DNS name to a pointer of 2 bytes but leaving `RDLENGTH` at 11 bytes, which causes an error when parsing the package further. At my university the initial DNS packages already had it compressed, which is why DNS resolution worked there. When I run a local `dnsmasq` server in between, it fails again.

**Comment by legal90** [comment]
Today the new update for Parallels Desktop 11 has been released: [11.1.0 (32202)](http://kb.parallels.com/en/123410)

And this issue should be fixed there. @mtneug, please verify.

**Comment by mtneug** [comment]
I can confirm that it is working with the new release. Thanks for the quick patch!

**Comment by satblip** [comment]
I'm on `11.1.1 (32312)` and I still have the issue.

My nameserver always reset to a 10.xx ip and the system is unable to resolve.

**Comment by legal90** [comment]
@satblip What boot2docker version is in your VM? (`docker-machine ssh dev -- docker version`)
If it's less that 1.9.1, please upgrade it (`docker-machine upgrade dev`) and then try to reproduce the issue again.

**Comment by satblip** [comment]
I've the latest version and already have recreated my VM from scratch

```bash
$ docker-machine ssh dev -- docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by dskr99** [comment]
Hi,
I've sent you an email a couple of days ago (to the address in your profile); most likely it was filtered somewhere. We'd appreciate if you could collect the next information:

1) Turn on detailed logging in Parallels (Parallels Desktop -> Preferences -> Advanced -> select "Use detailed log messages"
2) in guest start the command "sudo tcpdump -i eth0 -s 65535 -w dump.pcap"
3) reproduce the problem and stop the tcpdump
4) send a problem report (Parallels Desktop -> Help -> Send technical data) and the turn off detailed logging

Then send me the file dump.pcap and problem report number

**Comment by satblip** [comment]
Hi @dskr99,

thanks for the following, I had seen your email, but with the holidays period, I'm less on my computer and more with my family ;)

Actually, I don't have the issue anymore, so I'm looking to the why I had it. Multiple options there.

- VM paused due to low battery
- Internet location change
- Mis-usage somehow

But, as far as I know, all these 3 options should have been fixed by the delete and re-creation of the VM, no?

I'll keep you posted when I've more information.

Best wishes!

**Comment by dskr99** [comment]
:) In my country we still have Christmas at 7 january.

About reason of the issue it is hard to say.. since I work with networking, I tend to look at this kind of problems first. But of course it could be any of it. I'd appreciate if you could collect the information if this ever reproduces again.
